
export const NATIONAL_CURRICULUM_COURSES = [
  "Advanced Pakistan Studies Grades XI-XII",
  "Arabic Grades VI-VIII",
  "Arabic Grades XI-XII",
  "Art and Model Grades IX-X",
  "Biology Grades IX-XI",
  "Biology Grades XI-XII",
  "Chemistry Grades IX-X",
  "Chemistry Grades XI-XII",
  "Civics Grades IX-XII",
  "Computer Education Grades VI-VIII",
  "Computer Science Grades IX-XII",
  "Drawing Grades VI-VIII",
  "Early Childhood Education",
  "English Grades I-XII",
  "Ethics Grades III-XII",
  "Essentials of Home Economics Grades VI-VIII",
  "Essentials of Home Economics Grades IX-X",
  "Farsi Grades VI-VIII",
  "Fine Art Grades XI-XII",
  "Food and Nutrition IX-X",
  "General Knowledge Grades I-III",
  "General Maths Grades IX-X (Humanities Group)",
  "General Maths Grades XI-XII",
  "General Science Grades IV-VIII",
  "General Science Grades IX-X",
  "Geography Grades VI-VIII",
  "Health and Physical Education Grades VI-XII",
  "History Grades VI-VIII",
  "Introduction to Technologies VI-VIII",
  "Islamiat Grades III-XII",
  "Islamiat Grades IX-XII",
  "Islamiat Grades XI-XII",
  "Literacy Curriculum",
  "Library Science Grade XI-XII",
  "Mathematics Grades I-XII",
  "Pakistan Studies IX-X",
  "Physics Grades IX-X",
  "Physics Grades XI-XII",
  "Sindhi Grades I-X",
  "Social Studies IV-V",
  "Statistics Grades XI-XII",
  "Textile and Clothing Grades IX-X",
  "Urdu Grades I-XII"
];

export const SINDH_CURRICULUM_COURSES = [
  "Advanced Pakistan Studies Grade XI-XII (Revised 2021)",
  "Aasan Sindhi Grade III-V (2024)",
  "Aasan Sindhi Grade VI-VII (2025)",
  "Aasan Urdu Grade III-V (2024)",
  "Biology Grade IX-XII (2024) [aligned with N.C.C]",
  "Biology Grade XI-XII (2019)",
  "Chemistry Grade IX-XII (2024) [aligned with N.C.C]",
  "Chemistry Grade IX-X (2017)",
  "Chemistry Grade XI-XII (2019)",
  "Computer Science Grade VI-VIII (2024) [aligned with N.C.C]",
  "Computer Science Grade IX-XIII (2024) [aligned with N.C.C]",
  "Computer Science Grade XI-XII (2019)",
  "Computer Science Grade IX-X (2018)",
  "Disaster Risk Reduction Integration into Education Grade I-VIII (2020)",
  "Drawing Grades VI-VIII (2022)",
  "Early Childhood Care & Education Standards for Sindh (2018)",
  "Early Childhood Care & Education 2018 (New Version)",
  "Early Childhood Education (2024) [aligned with N.C.C]",
  "English Language Grade K-VIII (2024) [aligned with N.C.C]",
  "English Language Grade IX-XII (2024) [aligned with N.C.C]",
  "English Language Grade ECE-XII (2016)",
  "English Literature Grade XI-XII [Revised] 2019",
  "Ethics Grade III-V (2019)",
  "Ethics Grade VI-VIII (2020)",
  "Ethics Grade XI-XII (2020)",
  "General Science Grade IV-VIII (2024) [aligned with N.C.C]",
  "General Knowledge Grade I-III (2024)",
  "Islamiat Grade III-VIII",
  "Islamiat Grade IX-X",
  "Islamiat Grade XI-XII",
  "It's All One Curriculum: Curriculum Guidelines for Life Skills Based Education",
  "Library Science Grade XI-XII [aligned with N.C.C]",
  "Mathematics Grade I-VIII (2024) [aligned with N.C.C]",
  "Mathematics Grade IX-XII (2024) [aligned with N.C.C]",
  "Mathematics Grade XI-XII (2019)",
  "Pakistan Studies Grade IX-X (2019)",
  "Pakistan Studies Grade IX-X (2019-20) Revised",
  "Physical Education Grade I-VIII (2019)",
  "Physics Grade IX-XII (2024) [aligned with N.C.C]",
  "Physics Grade IX-X (2018)",
  "Physics Grade XI-XII (2019)",
  "Religious Studies Grade III-V (2022)",
  "Religious Studies Grade VI-VIII (2022)",
  "Religious Studies Grade IX-X (2022)",
  "Religious Studies Grade XI-XII (2022)",
  "Social Studies Grade IV-V (2024-25)",
  "Social Studies Grade VI-VIII (2015-16) [New Version]",
  "Sindhi Language Grade I-V (2018)",
  "Sindhi Language Grade VI-VIII (2022)",
  "Sindhi Language Grade XI-XII (2019)",
  "Urdu Language Grade I-V (2018)",
  "Urdu Language Grade VI-VIII (2023)",
  "Urdu Language Grade XI-XII (2019)"
];

export const PUNJAB_CURRICULUM_COURSES = [
  // Class Pre-I to II
  "Class Pre-I-II: Primer Mathematics",
  "Class Pre-I-II: Primer English",
  "Class Pre-I-II: Primer Urdu",
  "Class Pre-I-II: Neela Qaida (Optional)",
  "Class Pre-I-II: Tajveedi Qaida",
  "Class-I: Urdu-1",
  "Class-I: English-1",
  "Class-I: Math-1",
  "Class-I: Waqfiyat-e-Aama",
  "Class-I: Islamiat",
  "Class-I: Akhlaqiat (Optional)",
  "Class-I: Nazra Quran",
  "Class-II: Urdu-2",
  "Class-II: English-2",
  "Class-II: Math-2",
  
  // Class III
  "Class-III: Nazra Quran",
  "Class-III: Urdu-3",
  "Class-III: English-3",
  "Class-III: Math-3",
  "Class-III: Waqfiyat-e-Aama",
  "Class-III: Islamiat",
  "Class-III: Akhlaqiat (Optional)",

  // Class IV
  "Class-IV: Nazra Quran",
  "Class-IV: Urdu-4",
  "Class-IV: English-4",
  "Class-IV: Math-4",
  "Class-IV: General Science-4",
  "Class-IV: Islamiat-4",
  "Class-IV: Masharti Aloom-4",
  "Class-IV: Akhlaqiat (Optional)",

  // Class V
  "Class-V: Nazra Quran",
  "Class-V: Urdu-5",
  "Class-V: English-5",
  "Class-V: Math-5",
  "Class-V: General Science",
  "Class-V: Islamiat",
  "Class-V: Masharti Aloom-5",
  "Class-V: Akhlaqiat (Optional)",

  // Class VI
  "Class-VI: Translation of the Holy Quran",
  "Class-VI: Urdu",
  "Class-VI: English",
  "Class-VI: Islamiat",
  "Class-VI: Geography",
  "Class-VI: History",
  "Class-VI: Ethics",
  "Class-VI: Arabic",
  "Class-VI: Mathematics",
  "Class-VI: General Science",
  "Class-VI: Computer Science",
  "Class-VI: Art & Drawing",
  "Class-VI: Zari Taleem",
  "Class-VI: Punjabi",
  "Class-VI: Farsi",
  "Class-VI: Itlaqi Barqiat",
  "Class-VI: Home Economics",

  // Class VII
  "Class-VII: Translation of the Holy Quran",
  "Class-VII: Islamiat",
  "Class-VII: Arabic",
  "Class-VII: Urdu",
  "Class-VII: Ethics",
  "Class-VII: Geography",
  "Class-VII: History",
  "Class-VII: Mathematics",
  "Class-VII: English",
  "Class-VII: Computer Science",
  "Class-VII: General Science",
  "Class-VII: Art & Drawing",
  "Class-VII: Punjabi",
  "Class-VII: Farsi",
  "Class-VII: Zari Taleem",
  "Class-VII: Itlaqi Barqiat",
  "Class-VII: Home Economics",

  // Class VIII
  "Class-VIII: Translation of the Holy Quran",
  "Class-VIII: English",
  "Class-VIII: Mathematics",
  "Class-VIII: Geography",
  "Class-VIII: History",
  "Class-VIII: General Science",
  "Class-VIII: Computer Science",
  "Class-VIII: Urdu",
  "Class-VIII: Islamiat",
  "Class-VIII: Arabic (Optional)",
  "Class-VIII: Ethics",
  "Class-VIII: Art & Drawing",
  "Class-VIII: Punjabi",
  "Class-VIII: Farsi",
  "Class-VIII: Zari Taleem",
  "Class-VIII: Itlaqi Barqiat",
  "Class-VIII: Home Economics",

  // Class IX
  "Class-IX: Translation of the Holy Quran",
  "Class-IX: Islamiat",
  "Class-IX: Urdu",
  "Class-IX: English",
  "Class-IX: General Mathematics",
  "Class-IX: Mathematics (Science)",
  "Class-IX: Physics",
  "Class-IX: Chemistry",
  "Class-IX: Biology",
  "Class-IX: Computer Science",
  "Class-IX: Pakistan Studies",
  "Class-IX: Akhlaqiat",
  "Class-IX: Art & Model Drawing",
  "Class-IX: Home Economics",
  "Class-IX: Ghiza aur Ghizaiyat",
  "Class-IX: Textile and Clothing",
  "Class-IX: Physics Practical",
  "Class-IX: Chemistry Practical",
  "Class-IX: Biology Practical",
  "Class-IX: Biotechnology",
  "Class-IX: Computer & Entrepreneurship",
  "Class-IX: Agriculture Science",
  "Class-IX: Communication Skills",
  "Class-IX: Fashion Design",
  "Class-IX: ICT",
  "Class-IX: Health Sciences",

  // Class X
  "Class-X: Translation of the Holy Quran",
  "Class-X: Mathematics (Science)",
  "Class-X: General Mathematics",
  "Class-X: Physics",
  "Class-X: Chemistry",
  "Class-X: Biology",
  "Class-X: Computer Science",
  "Class-X: Urdu (Compulsory)",
  "Class-X: Pakistan Studies",
  "Class-X: Akhlaqiat",
  "Class-X: Islamiat",
  "Class-X: English",
  "Class-X: Art & Model Drawing",
  "Class-X: Home Economics",
  "Class-X: Ghiza aur Ghizaiyat",
  "Class-X: Textile and Clothing",
  "Class-X: Physics Practical",
  "Class-X: Chemistry Practical",
  "Class-X: Biology Practical",
  "Class-X: Farsi",
  "Class-X: General Science",
  "Class-X: English Grammar & Composition",
  "Class-X: Urdu Quaid-e-Insha",
  "Class-X: Economics",
  "Class-X: Punjabi (Optional)",
  "Class-X: Zari Taleem",
  "Class-X: Health & Physical Education",
  "Class-X: Education",
  "Class-X: Civics",
  "Class-X: Model Paper Islamiat",

  // Class XI
  "Class-XI: Translation of the Holy Quran",
  "Class-XI: Islamiat",
  "Class-XI: Physical Geography",
  "Class-XI: Urdu",
  "Class-XI: English (Short Stories)",
  "Class-XI: English Book III",
  "Class-XI: Mathematics",
  "Class-XI: Physics",
  "Class-XI: Economics",
  "Class-XI: Statistics",
  "Class-XI: Biology",
  "Class-XI: Chemistry",
  "Class-XI: Computer Science",
  "Class-XI: Civics",
  "Class-XI: Punjabi",
  "Class-XI: Ilm-ul-Taleem",
  "Class-XI: Farsi",
  "Class-XI: Psychology",
  "Class-XI: Philosophy",
  "Class-XI: Akhlaqiat",

  // Class XII
  "Class-XII: Translation of the Holy Quran",
  "Class-XII: Human Geography",
  "Class-XII: Urdu",
  "Class-XII: Pakistan Studies",
  "Class-XII: English Book II",
  "Class-XII: Biology",
  "Class-XII: Chemistry",
  "Class-XII: Mathematics",
  "Class-XII: Physics",
  "Class-XII: Civics",
  "Class-XII: Economics",
  "Class-XII: Statistics",
  "Class-XII: Computer Science",
  "Class-XII: Farsi",
  "Class-XII: Punjabi",
  "Class-XII: Psychology",
  "Class-XII: Logic",
  "Class-XII: Ilm-ul-Taleem",
  "Class-XII: Akhlaqiat",

  // Additional
  "Akhlaqiat Class 11-12 (Optional)",
  "Geography Workbook",
  "Health & Physical Education",
  "English Grammar & Composition (11-12)",
  "Urdu Quaid-e-Insha (11-12)",
  "Home Economics (11-12)"
];

export const CURRICULUM_DATA: Record<string, string[]> = {
  "National Curriculum (dcar.gos.pk)": NATIONAL_CURRICULUM_COURSES,
  "Sindh Curriculum (dcar.gos.pk)": SINDH_CURRICULUM_COURSES,
  "Punjab Curriculum (pctb.punjab.gov.pk)": PUNJAB_CURRICULUM_COURSES
};

export const getCurriculumSources = () => Object.keys(CURRICULUM_DATA);
export const getCoursesForSource = (source: string) => CURRICULUM_DATA[source] || [];
export const getCourses = () => NATIONAL_CURRICULUM_COURSES; // Fallback for backward compatibility if needed
